### ISSUE TITLE
not working when using with spring security rest

### ISSUE THREAD

**Issue by niraj-sesan-dev** [ataylor284/spring-security-eventlog#7]
| Error 2015-09-01 16:22:33,839 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'restTokenValidationFilter': Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'org.springframework.security.authentication.DefaultAuthenticationEventPublisher' to required type 'grails.plugin.springsecurity.rest.authentication.RestAuthenticationEventPublisher' for property 'authenticationEventPublisher'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.springframework.security.authentication.DefaultAuthenticationEventPublisher] to required type [grails.plugin.springsecurity.rest.authentication.RestAuthenticationEventPublisher] for property 'authenticationEventPublisher': no matching editors or conversion strategy found
Message: Error creating bean with name 'restTokenValidationFilter': Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'org.springframework.security.authentication.DefaultAuthenticationEventPublisher' to required type 'grails.plugin.springsecurity.rest.authentication.RestAuthenticationEventPublisher' for property 'authenticationEventPublisher'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.springframework.security.authentication.DefaultAuthenticationEventPublisher] to required type [grails.plugin.springsecurity.rest.authentication.RestAuthenticationEventPublisher] for property 'authenticationEventPublisher': no matching editors or conversion strategy found
    Line | Method
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by ConversionNotSupportedException: Failed to convert property value of type 'org.springframework.security.authentication.DefaultAuthenticationEventPublisher' to required type 'grails.plugin.springsecurity.rest.authentication.RestAuthenticationEventPublisher' for property 'authenticationEventPublisher'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.springframework.security.authentication.DefaultAuthenticationEventPublisher] to required type [grails.plugin.springsecurity.rest.authentication.RestAuthenticationEventPublisher] for property 'authenticationEventPublisher': no matching editors or conversion strategy found
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by IllegalStateException: Cannot convert value of type [org.springframework.security.authentication.DefaultAuthenticationEventPublisher] to required type [grails.plugin.springsecurity.rest.authentication.RestAuthenticationEventPublisher] for property 'authenticationEventPublisher': no matching editors or conversion strategy found
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
| Error Forked Grails VM exited with error

**Comment by ataylor284** [comment]
Ok, this issue should be fixed.  Note that you'll need grails.plugin.springsecurity.useSecurityEventListener set to true in your Config.groovy to get the rest plugin to publish security events.
